### get persons
GET http://localhost:3001/api/persons

### info
GET http://localhost:3001/info

### info from fly
GET https://phonebook-sjm.fly.dev/info

### get 1 person from mongoDB
GET http://localhost:3001/api/persons/661f7c1ffeb4a2579a4686e2

### non-existing id
GET http://localhost:3001/api/persons/661f7c1ffeb4a2579a4686e3

### delete
DELETE http://localhost:3001/api/persons/2

### create

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Lars Hansen", 
    "number": "12345678"
}

### create without number

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No number"
}
