### get persons
GET http://localhost:3001/api/persons

### info
GET http://localhost:3001/info

### info from fly
GET https://phonebook-sjm.fly.dev/info

### get 1 person from mongoDB
GET http://localhost:3001/api/persons/661f7c1ffeb4a2579a4686e2

### non-existing id, returns 404
GET http://localhost:3001/api/persons/661f7c1ffeb4a2579a4686e3

### get with wrong id format - CastError returns 400 Bad Request
GET http://localhost:3001/api/persons/135

### delete
DELETE http://localhost:3001/api/persons/661fa9e184250a8ae639bc12

### delete with wrong id format - CastError returns 400 Bad Request
DELETE http://localhost:3001/api/persons/661

### create. 200 Ok
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Lars Hansen", 
    "number": "09-1234556"
}

### create without number
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No number"
}

### create with too short name. Should return 400, Person validation failed...
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Ny", 
    "number": "44444444"
}

### create with invalid number. Returns 400, Person validation failed: number: 12345678 is not a valid phone number!
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Invalid number",
    "number": "1234-5678"
}

### update
PUT http://localhost:3001/api/persons/661f7c1ffeb4a2579a4686e2 HTTP/1.1
content-type: application/json

{
    "name": "Sissel", 
    "number": "66666"
}

