### get persons
GET http://localhost:3001/api/persons

### info
GET http://localhost:3001/info

### get 1 person
GET http://localhost:3001/api/persons/1

### non-existing id
GET http://localhost:3001/api/persons/145

### delete
DELETE http://localhost:3001/api/persons/2

### create

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Lars Hansen", 
    "number": "12345678"
}

### create without number

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "No number"
}
